owner: smithfield-studio
repo: status

sites:
  - name: Smithfield
    url: https://smithfield.studio
  - name: Change.org
    url: https://changefoundation.org
  - name: Wooshii
    url: https://wooshii.com
  - name: Oneflow
    url: https://oneflow.com
  - name: WWF Planet-Based Diets
    url: https://planetbaseddiets.panda.org
  - name: AFRIpads
    url: https://www.afripads.com
  - name: Kindness
    url: https://kindness.org

status-website:
  cname: status.smithfield.studio
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Smithfield Status
  introTitle: "**Smithfield** clients site uptime/status"
  introMessage: Powered by the amazing open source [Upptime project](https://github.com/upptime/upptime) ❤️
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Smithfield Studio
      href: https://smithfield.studio/


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
